name: CI

on:
  push:

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        persist-credentials: false
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'
        architecture: 'x64'
    - name: Install build tools
      run: |
        python -m pip install --upgrade build twine
    - name: Build package
      run: |
        python -m build
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: ./dist
  integration-test:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python: ["3.6", "3.7", "3.8", "3.9"]
        experimental: [false]
        include:
          - os: ubuntu-latest
            python: "3.10.0-beta.4"
            experimental: true
    continue-on-error: ${{ matrix.experimental }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        persist-credentials: false
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        architecture: 'x64'
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: ./dist
    - name: Test install
      run: |
        python -m pip install ./dist/schemdule-0.0.2-py3-none-any.whl
    - name: Test run through python
      run: |
        python -m schemdule demo
    - name: Test run directly
      run: |
        schemdule demo